apiVersion: v1
kind: Service
metadata:
  name: currencies-name-service
  labels:
    app: currencies-name
spec:
  type: ClusterIP
  selector:
    app: currencies-name
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  sessionAffinity: None