apiVersion: v1
kind: Service
metadata:
  name: languages-service
  labels:
    app: languages
spec:
  type: ClusterIP
  selector:
    app: languages
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  sessionAffinity: None