apiVersion: v1
kind: Service
metadata:
  name: currencies-symbol-service
  labels:
    app: currencies-symbol
spec:
  type: ClusterIP
  selector:
    app: currencies-symbol
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  sessionAffinity: None