const currenciesCode = {
  Afghanistan: 'AFN',
  Albania: 'ALL',
  Algeria: 'DZD',
  'American Samoa': 'USD',
  Andorra: 'EUR',
  Angola: 'AOA',
  Anguilla: 'XCD',
  'Antigua and Barbuda': 'XCD',
  Argentina: 'ARS',
  Armenia: 'AMD',
  Aruba: 'AWG',
  Australia: 'AUD',
  Azerbaijan: 'AZN',
  Bahamas: 'BSD',
  Bahrain: 'BHD',
  Bangladesh: 'BDT',
  Barbados: 'BBD',
  Belarus: 'BYN',
  Belgium: 'EUR',
  Belize: 'BZD',
  Benin: 'XOF',
  Bermuda: 'BMD',
  Bhutan: 'BTN',
  'Bolivia (Plurinational State of)': 'BOB',
  'Bosnia and Herzegovina': 'BAM',
  Botswana: 'BWP',
  Brazil: 'BRL',
  'British Indian Ocean Territory': 'USD',
  'Virgin Islands (British)': 'USD',
  'Virgin Islands (U.S.)': 'USD',
  'Brunei Darussalam': 'BND',
  Bulgaria: 'BGN',
  'Burkina Faso': 'XOF',
  Burundi: 'BIF',
  Cambodia: 'KHR',
  Cameroon: 'XAF',
  Canada: 'CAD',
  'Cabo Verde': 'CVE',
  'Cayman Islands': 'KYD',
  'Central African Republic': 'XAF',
  Chile: 'CLP',
  China: 'CNY',
  Colombia: 'COP',
  Comoros: 'KMF',
  Congo: 'XAF',
  'Congo (Democratic Republic of the)': 'CDF',
  'Cook Islands': 'NZD',
  'Costa Rica': 'CRC',
  Croatia: 'HRK',
  Cuba: 'CUC',
  Cyprus: 'EUR',
  'Czech Republic': 'CZK',
  Denmark: 'DKK',
  Djibouti: 'DJF',
  Dominica: 'XCD',
  'Dominican Republic': 'DOP',
  Ecuador: 'USD',
  Egypt: 'EGP',
  'El Salvador': 'USD',
  'Equatorial Guinea': 'XAF',
  Eritrea: 'ERN',
  Estonia: 'EUR',
  Ethiopia: 'ETB',
  'Falkland Islands (Malvinas)': 'FKP',
  'Faroe Islands': 'DKK',
  Fiji: 'FJD',
  Finland: 'EUR',
  France: 'EUR',
  'French Guiana': 'EUR',
  'French Polynesia': 'XPF',
  Gabon: 'XAF',
  Gambia: 'GMD',
  Georgia: 'GEL',
  Germany: 'EUR',
  Ghana: 'GHS',
  Gibraltar: 'GIP',
  Greece: 'EUR',
  Greenland: 'DKK',
  Grenada: 'XCD',
  Guadeloupe: 'EUR',
  Guam: 'USD',
  Guatemala: 'GTQ',
  Guinea: 'GNF',
  'Guinea-Bissau': 'XOF',
  Guyana: 'GYD',
  Haiti: 'HTG',
  'Holy See': 'EUR',
  Honduras: 'HNL',
  'Hong Kong': 'HKD',
  Hungary: 'HUF',
  Iceland: 'ISK',
  India: 'INR',
  Indonesia: 'IDR',
  "Côte d'Ivoire": 'XOF',
  'Iran (Islamic Republic of)': 'IRR',
  Iraq: 'IQD',
  Ireland: 'EUR',
  Israel: 'ILS',
  Italy: 'EUR',
  Jamaica: 'JMD',
  Japan: 'JPY',
  Jordan: 'JOD',
  Kazakhstan: 'KZT',
  Kenya: 'KES',
  Kiribati: 'AUD',
  Kuwait: 'KWD',
  Kyrgyzstan: 'KGS',
  "Lao People's Democratic Republic": 'LAK',
  Latvia: 'EUR',
  Lebanon: 'LBP',
  Lesotho: 'LSL',
  Liberia: 'LRD',
  Libya: 'LYD',
  Liechtenstein: 'CHF',
  Lithuania: 'EUR',
  Luxembourg: 'EUR',
  Macao: 'MOP',
  'Macedonia (the former Yugoslav Republic of)': 'MKD',
  Madagascar: 'MGA',
  Malawi: 'MWK',
  Malaysia: 'MYR',
  Maldives: 'MVR',
  Mali: 'XOF',
  Malta: 'EUR',
  'Marshall Islands': 'USD',
  Martinique: 'EUR',
  Mauritania: 'MRO',
  Mauritius: 'MUR',
  Mayotte: 'EUR',
  Mexico: 'MXN',
  'Micronesia (Federated States of)': 'USD',
  'Moldova (Republic of)': 'MDL',
  Monaco: 'EUR',
  Mongolia: 'MNT',
  Montenegro: 'EUR',
  Montserrat: 'XCD',
  Morocco: 'MAD',
  Mozambique: 'MZN',
  Myanmar: 'MMK',
  Namibia: 'NAD',
  Nauru: 'AUD',
  Nepal: 'NPR',
  Netherlands: 'EUR',
  'New Caledonia': 'XPF',
  'New Zealand': 'NZD',
  Nicaragua: 'NIO',
  Niger: 'XOF',
  Nigeria: 'NGN',
  Niue: 'NZD',
  'Norfolk Island': 'AUD',
  "Korea (Democratic People's Republic of)": 'KPW',
  'Northern Mariana Islands': 'USD',
  Norway: 'NOK',
  Oman: 'OMR',
  Pakistan: 'PKR',
  Palau: 'USD',
  'Palestine, State of': 'ILS',
  Panama: 'USD',
  'Papua New Guinea': 'PGK',
  Paraguay: 'PYG',
  Peru: 'PEN',
  Philippines: 'PHP',
  Poland: 'PLN',
  Portugal: 'EUR',
  'Puerto Rico': 'USD',
  Qatar: 'QAR',
  'Republic of Kosovo': 'EUR',
  'Réunion': 'EUR',
  Romania: 'RON',
  'Russian Federation': 'RUB',
  Rwanda: 'RWF',
  'Saint Barthélemy': 'EUR',
  'Saint Helena, Ascension and Tristan da Cunha': 'SHP',
  'Saint Kitts and Nevis': 'XCD',
  'Saint Lucia': 'XCD',
  'Saint Martin (French part)': 'EUR',
  'Saint Pierre and Miquelon': 'EUR',
  'Saint Vincent and the Grenadines': 'XCD',
  Samoa: 'WST',
  'San Marino': 'EUR',
  'Sao Tome and Principe': 'STD',
  'Saudi Arabia': 'SAR',
  Senegal: 'XOF',
  Serbia: 'RSD',
  Seychelles: 'SCR',
  'Sierra Leone': 'SLL',
  Singapore: 'SGD',
  Slovakia: 'EUR',
  Slovenia: 'EUR',
  'Solomon Islands': 'SBD',
  Somalia: 'SOS',
  'South Africa': 'ZAR',
  'Korea (Republic of)': 'KRW',
  Spain: 'EUR',
  'Sri Lanka': 'LKR',
  Sudan: 'SDG',
  Suriname: 'SRD',
  Swaziland: 'SZL',
  Sweden: 'SEK',
  Switzerland: 'CHF',
  'Syrian Arab Republic': 'SYP',
  Taiwan: 'TWD',
  Tajikistan: 'TJS',
  'Tanzania, United Republic of': 'TZS',
  Thailand: 'THB',
  'Timor-Leste': 'USD',
  Togo: 'XOF',
  Tokelau: 'NZD',
  Tonga: 'TOP',
  'Trinidad and Tobago': 'TTD',
  Tunisia: 'TND',
  Turkey: 'TRY',
  Turkmenistan: 'TMT',
  'Turks and Caicos Islands': 'USD',
  Tuvalu: 'AUD',
  Uganda: 'UGX',
  Ukraine: 'UAH',
  'United Arab Emirates': 'AED',
  'United Kingdom of Great Britain and Northern Ireland': 'GBP',
  'United States of America': 'USD',
  Uruguay: 'UYU',
  Uzbekistan: 'UZS',
  Vanuatu: 'VUV',
  'Venezuela (Bolivarian Republic of)': 'VEF',
  'Viet Nam': 'VND',
  'Wallis and Futuna': 'XPF',
  Yemen: 'YER',
  Zambia: 'ZMW',
  Zimbabwe: 'BWP'
}

module.exports = {
  currenciesCode
}