const currenciesSymbol = {
  Afghanistan: '؋',
  Albania: 'L',
  Algeria: 'د.ج',
  'American Samoa': '$',
  Andorra: '€',
  Angola: 'Kz',
  Anguilla: '$',
  'Antigua and Barbuda': '$',
  Argentina: '$',
  Armenia: null,
  Aruba: 'ƒ',
  Australia: '$',
  Azerbaijan: null,
  Bahamas: '$',
  Bahrain: '.د.ب',
  Bangladesh: '৳',
  Barbados: '$',
  Belarus: 'Br',
  Belgium: '€',
  Belize: '$',
  Benin: 'Fr',
  Bermuda: '$',
  Bhutan: 'Nu.',
  'Bolivia (Plurinational State of)': 'Bs.',
  'Bosnia and Herzegovina': null,
  Botswana: 'P',
  Brazil: 'R$',
  'British Indian Ocean Territory': '$',
  'Virgin Islands (British)': '$',
  'Virgin Islands (U.S.)': '$',
  'Brunei Darussalam': '$',
  Bulgaria: 'лв',
  'Burkina Faso': 'Fr',
  Burundi: 'Fr',
  Cambodia: '៛',
  Cameroon: 'Fr',
  Canada: '$',
  'Cabo Verde': 'Esc',
  'Cayman Islands': '$',
  'Central African Republic': 'Fr',
  Chile: '$',
  China: '¥',
  Colombia: '$',
  Comoros: 'Fr',
  Congo: 'Fr',
  'Congo (Democratic Republic of the)': 'Fr',
  'Cook Islands': '$',
  'Costa Rica': '₡',
  Croatia: 'kn',
  Cuba: '$',
  Cyprus: '€',
  'Czech Republic': 'Kč',
  Denmark: 'kr',
  Djibouti: 'Fr',
  Dominica: '$',
  'Dominican Republic': '$',
  Ecuador: '$',
  Egypt: '£',
  'El Salvador': '$',
  'Equatorial Guinea': 'Fr',
  Eritrea: 'Nfk',
  Estonia: '€',
  Ethiopia: 'Br',
  'Falkland Islands (Malvinas)': '£',
  'Faroe Islands': 'kr',
  Fiji: '$',
  Finland: '€',
  France: '€',
  'French Guiana': '€',
  'French Polynesia': 'Fr',
  Gabon: 'Fr',
  Gambia: 'D',
  Georgia: 'ლ',
  Germany: '€',
  Ghana: '₵',
  Gibraltar: '£',
  Greece: '€',
  Greenland: 'kr',
  Grenada: '$',
  Guadeloupe: '€',
  Guam: '$',
  Guatemala: 'Q',
  Guinea: 'Fr',
  'Guinea-Bissau': 'Fr',
  Guyana: '$',
  Haiti: 'G',
  'Holy See': '€',
  Honduras: 'L',
  'Hong Kong': '$',
  Hungary: 'Ft',
  Iceland: 'kr',
  India: '₹',
  Indonesia: 'Rp',
  "Côte d'Ivoire": 'Fr',
  'Iran (Islamic Republic of)': '﷼',
  Iraq: 'ع.د',
  Ireland: '€',
  Israel: '₪',
  Italy: '€',
  Jamaica: '$',
  Japan: '¥',
  Jordan: 'د.ا',
  Kazakhstan: null,
  Kenya: 'Sh',
  Kiribati: '$',
  Kuwait: 'د.ك',
  Kyrgyzstan: 'с',
  "Lao People's Democratic Republic": '₭',
  Latvia: '€',
  Lebanon: 'ل.ل',
  Lesotho: 'L',
  Liberia: '$',
  Libya: 'ل.د',
  Liechtenstein: 'Fr',
  Lithuania: '€',
  Luxembourg: '€',
  Macao: 'P',
  'Macedonia (the former Yugoslav Republic of)': 'ден',
  Madagascar: 'Ar',
  Malawi: 'MK',
  Malaysia: 'RM',
  Maldives: '.ރ',
  Mali: 'Fr',
  Malta: '€',
  'Marshall Islands': '$',
  Martinique: '€',
  Mauritania: 'UM',
  Mauritius: '₨',
  Mayotte: '€',
  Mexico: '$',
  'Micronesia (Federated States of)': '$',
  'Moldova (Republic of)': 'L',
  Monaco: '€',
  Mongolia: '₮',
  Montenegro: '€',
  Montserrat: '$',
  Morocco: 'د.م.',
  Mozambique: 'MT',
  Myanmar: 'Ks',
  Namibia: '$',
  Nauru: '$',
  Nepal: '₨',
  Netherlands: '€',
  'New Caledonia': 'Fr',
  'New Zealand': '$',
  Nicaragua: 'C$',
  Niger: 'Fr',
  Nigeria: '₦',
  Niue: '$',
  'Norfolk Island': '$',
  "Korea (Democratic People's Republic of)": '₩',
  'Northern Mariana Islands': '$',
  Norway: 'kr',
  Oman: 'ر.ع.',
  Pakistan: '₨',
  Palau: '$',
  'Palestine, State of': '₪',
  Panama: '$',
  'Papua New Guinea': 'K',
  Paraguay: '₲',
  Peru: 'S/.',
  Philippines: '₱',
  Poland: 'zł',
  Portugal: '€',
  'Puerto Rico': '$',
  Qatar: 'ر.ق',
  'Republic of Kosovo': '€',
  'Réunion': '€',
  Romania: 'lei',
  'Russian Federation': '₽',
  Rwanda: 'Fr',
  'Saint Barthélemy': '€',
  'Saint Helena, Ascension and Tristan da Cunha': '£',
  'Saint Kitts and Nevis': '$',
  'Saint Lucia': '$',
  'Saint Martin (French part)': '€',
  'Saint Pierre and Miquelon': '€',
  'Saint Vincent and the Grenadines': '$',
  Samoa: 'T',
  'San Marino': '€',
  'Sao Tome and Principe': 'Db',
  'Saudi Arabia': 'ر.س',
  Senegal: 'Fr',
  Serbia: 'дин.',
  Seychelles: '₨',
  'Sierra Leone': 'Le',
  Singapore: '$',
  Slovakia: '€',
  Slovenia: '€',
  'Solomon Islands': '$',
  Somalia: 'Sh',
  'South Africa': 'R',
  'Korea (Republic of)': '₩',
  Spain: '€',
  'Sri Lanka': 'Rs',
  Sudan: 'ج.س.',
  Suriname: '$',
  Swaziland: 'L',
  Sweden: 'kr',
  Switzerland: 'Fr',
  'Syrian Arab Republic': '£',
  Taiwan: '$',
  Tajikistan: 'ЅМ',
  'Tanzania, United Republic of': 'Sh',
  Thailand: '฿',
  'Timor-Leste': '$',
  Togo: 'Fr',
  Tokelau: '$',
  Tonga: 'T$',
  'Trinidad and Tobago': '$',
  Tunisia: 'د.ت',
  Turkey: null,
  Turkmenistan: 'm',
  'Turks and Caicos Islands': '$',
  Tuvalu: '$',
  Uganda: 'Sh',
  Ukraine: '₴',
  'United Arab Emirates': 'د.إ',
  'United Kingdom of Great Britain and Northern Ireland': '£',
  'United States of America': '$',
  Uruguay: '$',
  Uzbekistan: null,
  Vanuatu: 'Vt',
  'Venezuela (Bolivarian Republic of)': 'Bs F',
  'Viet Nam': '₫',
  'Wallis and Futuna': 'Fr',
  Yemen: '﷼',
  Zambia: 'ZK',
  Zimbabwe: 'P'
}

module.exports = {
  currenciesSymbol
}